#!/bin/bash
# by Sylwester Arabas <slayoo@igf.fuw.edu.pl>
# part of GDL -- GNU Data Language

# LaTeX cleanup
rm -f *.tmp *.log gdl.ind gdl.toc gdl.aux gdl.out gdl.ild gdl.blg gdl.bbl gdl.ain gdldoc_tmp_*.pro gdl.ilg gdl.idx chapters/routine-list.tex

# removing empty routine files (automatically created by makeall)
for i in routines/*.tex; do if [ ! -s $i ]; then rm $i ; fi; done;

# removing examples output (all but the text and figure files which go into the CVS to track regressions)
for i in examples/*/*.out.tex; do rm $i; done;
for i in examples/*/*.out.pdf; do rm $i; done;
