extern "C" {
DLL_PUBLIC char *GDL_CDECL IDL_FileTermName(void) __attribute__((alias ("IDLGDL_FileTermName")));
DLL_PUBLIC char *GDL_CDECL IDL_MakeTempArray(int type, int n_dim, EXPORT_MEMINT  dim[], int init, EXPORT_VPTR *var) __attribute__((alias ("IDLGDL_MakeTempArray")));
DLL_PUBLIC char *GDL_CDECL IDL_MakeTempStruct(EXPORT_StructDefPtr sdef, int  n_dim, EXPORT_MEMINT *dim, EXPORT_VPTR *var, int zero) __attribute__((alias ("IDLGDL_MakeTempStruct")));
DLL_PUBLIC char *GDL_CDECL IDL_MakeTempStructVector(EXPORT_StructDefPtr sdef, EXPORT_MEMINT dim, EXPORT_VPTR *var, int zero) __attribute__((alias ("IDLGDL_MakeTempStructVector")));
DLL_PUBLIC char *GDL_CDECL IDL_MakeTempVector(int type, EXPORT_MEMINT dim, int  init, EXPORT_VPTR *var) __attribute__((alias ("IDLGDL_MakeTempVector")));
DLL_PUBLIC char *GDL_CDECL IDL_OutputFormatFunc(int type)  __attribute__((alias ("IDLGDL_OutputFormatFunc")));
DLL_PUBLIC char *GDL_CDECL IDL_ProgramNameFunc(void) __attribute__((alias ("IDLGDL_ProgramNameFunc")));
DLL_PUBLIC char *GDL_CDECL IDL_ProgramNameLCFunc(void) __attribute__((alias ("IDLGDL_ProgramNameLCFunc")));
DLL_PUBLIC char *GDL_CDECL IDL_StructTagNameByIndex(EXPORT_StructDefPtr sdef, int index, int msg_action, char **struct_name) __attribute__((alias ("IDLGDL_StructTagNameByIndex")));
DLL_PUBLIC char *GDL_CDECL IDL_SysRtnGetCurrentName(void) __attribute__((alias ("IDLGDL_SysRtnGetCurrentName")));
DLL_PUBLIC char *GDL_CDECL IDL_TypeNameFunc(int type)  __attribute__((alias ("IDLGDL_TypeNameFunc")));
DLL_PUBLIC char *GDL_CDECL IDL_VarMakeTempFromTemplate(EXPORT_VPTR template_var, int type, EXPORT_StructDefPtr sdef,  EXPORT_VPTR *result_addr, int zero) __attribute__((alias ("IDLGDL_VarMakeTempFromTemplate")));
DLL_PUBLIC char *GDL_CDECL IDL_VarName(EXPORT_VPTR v) __attribute__((alias ("IDLGDL_VarName")));
DLL_PUBLIC double  GDL_CDECL IDL_DoubleScalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_DoubleScalar")));
DLL_PUBLIC float  GDL_CDECL IDL_SysvValuesGetFloat(int type) __attribute__((alias ("IDLGDL_SysvValuesGetFloat")));
DLL_PUBLIC EXPORT_FILEINT  GDL_CDECL IDL_FILEINTScalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_FILEINTScalar")));
DLL_PUBLIC EXPORT_LONG64  GDL_CDECL IDL_Long64Scalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_Long64Scalar")));
DLL_PUBLIC EXPORT_LONG  GDL_CDECL IDL_LongScalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_LongScalar")));
DLL_PUBLIC EXPORT_LONG  GDL_CDECL IDL_SysvErrCodeValue(void) __attribute__((alias ("IDLGDL_SysvErrCodeValue")));
DLL_PUBLIC EXPORT_LONG  GDL_CDECL IDL_SysvErrorCodeValue(void) __attribute__((alias ("IDLGDL_SysvErrorCodeValue")));
DLL_PUBLIC EXPORT_LONG  GDL_CDECL IDL_SysvOrderValue(void) __attribute__((alias ("IDLGDL_SysvOrderValue")));
DLL_PUBLIC EXPORT_LONG *GDL_CDECL IDL_SysvSyserrorCodesAddr(void) __attribute__((alias ("IDLGDL_SysvSyserrorCodesAddr")));
DLL_PUBLIC EXPORT_MEMINT  GDL_CDECL IDL_MEMINTScalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_MEMINTScalar")));
DLL_PUBLIC EXPORT_MEMINT  GDL_CDECL IDL_StructTagInfoByIndex(EXPORT_StructDefPtr   sdef, int index, int msg_action, EXPORT_VPTR *var) __attribute__((alias ("IDLGDL_StructTagInfoByIndex")));
DLL_PUBLIC EXPORT_MEMINT  GDL_CDECL IDL_StructTagInfoByName(EXPORT_StructDefPtr sdef, char *name, int msg_action, EXPORT_VPTR *var)  __attribute__((alias ("IDLGDL_StructTagInfoByName")));
DLL_PUBLIC EXPORT_MEMINT  GDL_CDECL IDL_SysRtnNumEnabled(int is_function, int enabled) __attribute__((alias ("IDLGDL_SysRtnNumEnabled")));
DLL_PUBLIC EXPORT_MSG_BLOCK  GDL_CDECL IDL_MessageDefineBlock(char *block_name, int n, EXPORT_MSG_DEF *defs) __attribute__((alias ("IDLGDL_MessageDefineBlock")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvDirFunc(void) __attribute__((alias ("IDLGDL_SysvDirFunc")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvErrStringFunc(void) __attribute__((alias ("IDLGDL_SysvErrStringFunc")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvSyserrStringFunc(void) __attribute__((alias ("IDLGDL_SysvSyserrStringFunc")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvVersionArch(void) __attribute__((alias ("IDLGDL_SysvVersionArch")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvVersionOSFamily(void) __attribute__((alias ("IDLGDL_SysvVersionOSFamily")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvVersionOS(void) __attribute__((alias ("IDLGDL_SysvVersionOS")));
DLL_PUBLIC EXPORT_STRING *GDL_CDECL IDL_SysvVersionRelease(void) __attribute__((alias ("IDLGDL_SysvVersionRelease")));
DLL_PUBLIC EXPORT_StructDefPtr  GDL_CDECL IDL_MakeStruct(char *name, EXPORT_STRUCT_TAG_DEF *tags)  __attribute__((alias ("IDLGDL_MakeStruct")));
DLL_PUBLIC EXPORT_SYS_ERROR_STATE *GDL_CDECL IDL_SysvErrorStateAddr(void) __attribute__((alias ("IDLGDL_SysvErrorStateAddr")));
DLL_PUBLIC EXPORT_SYSRTN_GENERIC  GDL_CDECL IDL_SysRtnGetRealPtr(int is_function, char *name) __attribute__((alias ("IDLGDL_SysRtnGetRealPtr")));
DLL_PUBLIC EXPORT_ULONG64  GDL_CDECL IDL_ULong64Scalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_ULong64Scalar")));
DLL_PUBLIC EXPORT_ULONG  GDL_CDECL IDL_ULongScalar(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_ULongScalar")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_BasicTypeConversion(int argc, EXPORT_VPTR argv[], GDL_REGISTER int type) __attribute__((alias ("IDLGDL_BasicTypeConversion")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtByte(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtByte")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtBytscl(int argc, EXPORT_VPTR argv[], char *argk)  __attribute__((alias ("IDLGDL_CvtBytscl")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtComplex(int argc, EXPORT_VPTR argv[], char *argk=NULL)  __attribute__((alias ("IDLGDL_CvtComplex")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtDbl(int argc, EXPORT_VPTR argv[]) __attribute__((alias ("IDLGDL_CvtDbl")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtDComplex(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtDComplex")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtFILEINT(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtFILEINT")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtFix(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtFix")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtFlt(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtFlt")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtLng64(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtLng64")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtLng(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtLng")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtMEMINT(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtMEMINT")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtString(int argc, EXPORT_VPTR argv[], char *argk=NULL) __attribute__((alias ("IDLGDL_CvtString")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtUInt(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtUInt")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtULng64(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtULng64")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_CvtULng(int argc, EXPORT_VPTR argv[])  __attribute__((alias ("IDLGDL_CvtULng")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_FindNamedVariable(char *name, int ienter) __attribute__((alias ("IDLGDL_FindNamedVariable")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpByte(UCHAR value) __attribute__((alias ("IDLGDL_GettmpByte")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpDouble(double value) __attribute__((alias ("IDLGDL_GettmpDouble")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpFILEINT(EXPORT_FILEINT value)  __attribute__((alias ("IDLGDL_GettmpFILEINT")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpFloat(float value) __attribute__((alias ("IDLGDL_GettmpFloat")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpInt(EXPORT_INT value) __attribute__((alias ("IDLGDL_GettmpInt")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpLong64(EXPORT_LONG64 value) __attribute__((alias ("IDLGDL_GettmpLong64")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpLong(EXPORT_LONG value) __attribute__((alias ("IDLGDL_GettmpLong")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpMEMINT(EXPORT_MEMINT value) __attribute__((alias ("IDLGDL_GettmpMEMINT")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpObjRef(EXPORT_HVID value) __attribute__((alias ("IDLGDL_GettmpObjRef")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpPtr(EXPORT_HVID value) __attribute__((alias ("IDLGDL_GettmpPtr")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpUInt(EXPORT_UINT value) __attribute__((alias ("IDLGDL_GettmpUInt")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpULong64(EXPORT_ULONG64 vaGDL) __attribute__((alias ("IDLGDL_GettmpULong64")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GettmpULong(EXPORT_ULONG value) __attribute__((alias ("IDLGDL_GettmpULong")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_Gettmp(void) __attribute__((alias ("IDLGDL_Gettmp")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GetVarAddr1(char *name, int enter) __attribute__((alias ("IDLGDL_GetVarAddr1")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_GetVarAddr(char *name) __attribute__((alias ("IDLGDL_GetVarAddr")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_ImportArray(int n_dim, EXPORT_MEMINT dim[], int type, UCHAR *data, EXPORT_ARRAY_FREE_CB free_cb,  EXPORT_StructDefPtr s) __attribute__((alias ("IDLGDL_ImportArray")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_ImportNamedArray(char *name, int n_dim, EXPORT_MEMINT dim[],  int type, UCHAR *data,  EXPORT_ARRAY_FREE_CB free_cb, EXPORT_StructDefPtr s) __attribute__((alias ("IDLGDL_ImportNamedArray")));
DLL_PUBLIC EXPORT_VPTR  GDL_CDECL IDL_StrToSTRING(const char *s)  __attribute__((alias ("IDLGDL_StrToSTRING")));
DLL_PUBLIC int  GDL_CDECL IDL_AddSystemRoutine(EXPORT_SYSFUN_DEF *defs, int is_function, int cnt) __attribute__((alias ("IDLGDL_AddSystemRoutine")));
DLL_PUBLIC int  GDL_CDECL IDL_BailOut(int stop) __attribute__((alias ("IDLGDL_BailOut")));
DLL_PUBLIC int  GDL_CDECL IDL_Cleanup(int just_cleanup) __attribute__((alias ("IDLGDL_Cleanup")));
DLL_PUBLIC int  GDL_CDECL IDL_Execute(int argc, char *argv[]) __attribute__((alias ("IDLGDL_Execute")));
DLL_PUBLIC int  GDL_CDECL IDL_ExecuteStr(char *cmd)  __attribute__((alias ("IDLGDL_ExecuteStr")));
DLL_PUBLIC int  GDL_CDECL IDL_FileTermColumns(void) __attribute__((alias ("IDLGDL_FileTermColumns")));
DLL_PUBLIC int  GDL_CDECL IDL_FileTermIsTty(void) __attribute__((alias ("IDLGDL_FileTermIsTty")));
DLL_PUBLIC int  GDL_CDECL IDL_FileTermLines(void) __attribute__((alias ("IDLGDL_FileTermLines")));
DLL_PUBLIC int  GDL_CDECL IDL_GetExitStatus() __attribute__((alias ("IDLGDL_GetExitStatus")));
DLL_PUBLIC int  GDL_CDECL IDL_Initialize(EXPORT_INIT_DATA *init_data) __attribute__((alias ("IDLGDL_Initialize")));
DLL_PUBLIC int  GDL_CDECL IDL_Init(EXPORT_INIT_DATA_OPTIONS_T options, int *argc, char *argv[]) __attribute__((alias ("IDLGDL_Init")));
DLL_PUBLIC int  GDL_CDECL IDL_LMGRLicenseCheckout(char *szFeature, char *szVersion) __attribute__((alias ("IDLGDL_LMGRLicenseCheckout")));
DLL_PUBLIC int  GDL_CDECL IDL_LMGRLicenseCheckoutUnique(char *szFeature, char *szVersion) __attribute__((alias ("IDLGDL_LMGRLicenseCheckoutUnique")));
DLL_PUBLIC int  GDL_CDECL IDL_LMGRLicenseInfo(int iFlags) __attribute__((alias ("IDLGDL_LMGRLicenseInfo")));
DLL_PUBLIC int  GDL_CDECL IDL_LMGRSetLicenseInfo(int iFlags) __attribute__((alias ("IDLGDL_LMGRSetLicenseInfo")));
DLL_PUBLIC int  GDL_CDECL IDL_Load(void) __attribute__((alias ("IDLGDL_Load")));
DLL_PUBLIC int  GDL_CDECL IDL_Main(EXPORT_INIT_DATA_OPTIONS_T options, int argc, char *argv[]) __attribute__((alias ("IDLGDL_Main")));
DLL_PUBLIC int  GDL_CDECL IDL_MessageNameToCode(EXPORT_MSG_BLOCK block, const char *name) __attribute__((alias ("IDLGDL_MessageNameToCode")));
DLL_PUBLIC int  GDL_CDECL IDL_RuntimeExec(char *file) __attribute__((alias ("IDLGDL_RuntimeExec")));
DLL_PUBLIC int  GDL_CDECL IDL_StructNumTags(EXPORT_StructDefPtr sdef) __attribute__((alias ("IDLGDL_StructNumTags")));
DLL_PUBLIC int  GDL_CDECL IDL_SysRtnAdd(EXPORT_SYSFUN_DEF2 *defs, int is_function,int cnt) __attribute__((alias ("IDLGDL_SysRtnAdd")));
DLL_PUBLIC int GDL_CDECL IDL_TypeSizeFunc(int type)  __attribute__((alias ("IDLGDL_TypeSizeFunc")));
DLL_PUBLIC int  GDL_CDECL IDL_Win32Init(EXPORT_INIT_DATA_OPTIONS_T iOpts, void  *hinstExe, void *hwndExe, void *hAccel) __attribute__((alias ("IDLGDL_Win32Init")));
DLL_PUBLIC void GDL_CDECL IDL_DeleteDescriptors(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_DeleteDescriptors")));
DLL_PUBLIC void  GDL_CDECL IDL_Deltmp(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_Deltmp")));
DLL_PUBLIC void  GDL_CDECL IDL_ExitRegister(EXPORT_EXIT_HANDLER_FUNC proc) __attribute__((alias ("IDLGDL_ExitRegister")));
DLL_PUBLIC void  GDL_CDECL IDL_ExitUnregister(EXPORT_EXIT_HANDLER_FUNC proc) __attribute__((alias ("IDLGDL_ExitUnregister")));
DLL_PUBLIC void  GDL_CDECL IDL_Freetmp(GDL_REGISTER EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_Freetmp")));
DLL_PUBLIC  int  GDL_CDECL IDL_KWGetParams(int argc, EXPORT_VPTR *argv, char *argk_passed, GDL_KW_PAR *kw_requested, EXPORT_VPTR *plain_args, int mask)  __attribute__((alias ("IDLGDL_KWGetParams")));
DLL_PUBLIC void  GDL_CDECL IDL_KWFree(void) __attribute__((alias ("IDLGDL_KWFree")));
DLL_PUBLIC int   GDL_CDECL IDL_KWProcessByOffset(int argc, EXPORT_VPTR *argv, char *argk_passed, GDL_KW_PAR *kw_requested, EXPORT_VPTR *plain_args, int mask, void *kw_result) __attribute__((alias ("IDLGDL_KWProcessByOffset")));
DLL_PUBLIC void  GDL_CDECL IDL_Message_BADARRDNUM(int action) __attribute__((alias ("IDLGDL_Message_BADARRDNUM")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageErrnoFromBlock(EXPORT_MSG_BLOCK block, int code, ...) __attribute__((alias ("IDLGDL_MessageErrnoFromBlock")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageErrno(int code, ...) __attribute__((alias ("IDLGDL_MessageErrno")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageFromBlock(EXPORT_MSG_BLOCK block, int code, int action,...) __attribute__((alias ("IDLGDL_MessageFromBlock")));
DLL_PUBLIC void *GDL_CDECL IDL_MessageGJE(void) __attribute__((alias ("IDLGDL_MessageGJE")));
DLL_PUBLIC void  GDL_CDECL IDL_Message(int code, int action, ...)  __attribute__((alias ("IDLGDL_Message")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageResetSysvErrorState(void)  __attribute__((alias ("IDLGDL_MessageResetSysvErrorState")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageSJE(void *value) __attribute__((alias ("IDLGDL_MessageSJE")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageSyscodeFromBlock(EXPORT_MSG_BLOCK block, int code, EXPORT_MSG_SYSCODE_T syscode_type,  int syscode, int action, ...) __attribute__((alias ("IDLGDL_MessageSyscodeFromBlock")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageSyscode(int code, EXPORT_MSG_SYSCODE_T syscode_type, int syscode, int action, ...) __attribute__((alias ("IDLGDL_MessageSyscode")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVarErrorFromBlock(EXPORT_MSG_BLOCK block, int code, EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVarErrorFromBlock")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVarError(int code, EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVarError")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOCOMPLEX(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOCOMPLEX")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOCONST(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOCONST")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOEXPR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOEXPR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOFILE(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOFILE")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOMEMINT64(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOMEMINT64")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOOBJREF(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOOBJREF")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOPTR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOPTR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOSCALAR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOSCALAR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOSTRING(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOSTRING")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOSTRUCT(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOSTRUCT")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOTARRAY(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NOTARRAY")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NOTSCALAR(EXPORT_VPTR var, int action)__attribute__((alias ("IDLGDL_MessageVE_NOTSCALAR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_NULLSTR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_NULLSTR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_REQOBJREF(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_REQOBJREF")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_REQPTR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_REQPTR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_REQSTR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_REQSTR")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_STRUC_REQ(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_STRUC_REQ")));
DLL_PUBLIC void  GDL_CDECL IDL_MessageVE_UNDEFVAR(EXPORT_VPTR var, int action) __attribute__((alias ("IDLGDL_MessageVE_UNDEFVAR")));
DLL_PUBLIC void  GDL_CDECL IDL_PrintF(int argc, EXPORT_VPTR *argv, char *argk)  __attribute__((alias ("IDLGDL_PrintF")));
DLL_PUBLIC void  GDL_CDECL IDL_Print(int argc, EXPORT_VPTR *argv, char *argk)  __attribute__((alias ("IDLGDL_Print")));
DLL_PUBLIC void  GDL_CDECL IDL_Runtime(EXPORT_INIT_DATA_OPTIONS_T options, int *argc, char *argv[], char *file) __attribute__((alias ("IDLGDL_Runtime")));
DLL_PUBLIC void  GDL_CDECL IDL_StoreScalar(EXPORT_VPTR dest, int type,EXPORT_ALLTYPES * value)  __attribute__((alias ("IDLGDL_StoreScalar")));
DLL_PUBLIC void  GDL_CDECL IDL_StoreScalarZero(EXPORT_VPTR dest, int type)  __attribute__((alias ("IDLGDL_StoreScalarZero")));
DLL_PUBLIC void  GDL_CDECL IDL_StrDelete(EXPORT_STRING *str, EXPORT_MEMINT n)  __attribute__((alias ("IDLGDL_StrDelete")));
DLL_PUBLIC void  GDL_CDECL IDL_StrDup(GDL_REGISTER EXPORT_STRING *str, GDL_REGISTER EXPORT_MEMINT n) __attribute__((alias ("IDLGDL_StrDup")));
DLL_PUBLIC void  GDL_CDECL IDL_StrEnsureLength(EXPORT_STRING *s, int n)  __attribute__((alias ("IDLGDL_StrEnsureLength")));
DLL_PUBLIC void  GDL_CDECL IDL_StrStore(EXPORT_STRING *s, const char *fs) __attribute__((alias ("IDLGDL_StrStore")));
DLL_PUBLIC void  GDL_CDECL IDL_SysRtnEnable(int is_function, EXPORT_STRING *names, EXPORT_MEMINT n, int option,  EXPORT_SYSRTN_GENERIC disfcn) __attribute__((alias ("IDLGDL_SysRtnEnable")));
DLL_PUBLIC void  GDL_CDECL IDL_SysRtnGetEnabledNames(int is_function, EXPORT_STRING *str, int enabled) __attribute__((alias ("IDLGDL_SysRtnGetEnabledNames")));
DLL_PUBLIC void  GDL_CDECL IDL_VarCopy(GDL_REGISTER EXPORT_VPTR src, GDL_REGISTER EXPORT_VPTR dst) __attribute__((alias ("IDLGDL_VarCopy")));
DLL_PUBLIC void  GDL_CDECL IDL_VarEnsureSimple(EXPORT_VPTR v)  __attribute__((alias ("IDLGDL_VarEnsureSimple")));
DLL_PUBLIC void  GDL_CDECL IDL_VarGetData(EXPORT_VPTR v, EXPORT_MEMINT *n, char **pd,  int ensure_simple) __attribute__((alias ("IDLGDL_VarGetData")));
DLL_PUBLIC void  GDL_CDECL IDL_Win32MessageLoop(int fFlush) __attribute__((alias ("IDLGDL_Win32MessageLoop")));
DLL_PUBLIC void  GDL_CDECL IDL_WinCleanup(void) __attribute__((alias ("IDLGDL_WinCleanup")));
DLL_PUBLIC void  GDL_CDECL IDL_WinPostInit(void) __attribute__((alias ("IDLGDL_WinPostInit")));
extern int IDL_OutputFormatLen __attribute__((alias ("IDLGDL_OutputFormatLen")));
}
