// to be included from GDLInterpreter.hpp 
/*
BaseGDL*  constantNotOptimized(ProgNodeP _t);
RetCode  interactiveNotOptimized(ProgNodeP _t);
RetCode  statement_listNotOptimized(ProgNodeP _t);
RetCode  executeNotOptimized(ProgNodeP _t);
BaseGDL* call_funNotOptimized(ProgNodeP _t); // called from pythongdl.cpp
BaseGDL**  call_lfunNotOptimized(ProgNodeP _t);
void call_proNotOptimized(ProgNodeP _t); 
RetCode blockNotOptimized(ProgNodeP _t);
BaseGDL* exprNotOptimized(ProgNodeP _t);
BaseGDL**  l_simple_varNotOptimized(ProgNodeP _t);
BaseGDL*  sys_varNotOptimized(ProgNodeP _t); // *
BaseGDL* sys_var_nocopyNotOptimized(ProgNodeP _t);
BaseGDL* dot_exprNotOptimized(ProgNodeP _t);
BaseGDL* simple_varNotOptimized(ProgNodeP _t); // *
BaseGDL**  ref_parameterNotOptimized(ProgNodeP _t);
BaseGDL* unnamed_struct_defNotOptimized(ProgNodeP _t);
BaseGDL* lib_function_call_retnewNotOptimized(ProgNodeP _t); // *
BaseGDL*  lib_function_callNotOptimized(ProgNodeP _t);
BaseGDL* constant_nocopyNotOptimized(ProgNodeP _t); // *
BaseGDL* struct_defNotOptimized(ProgNodeP _t);
*/


