name: antlr

on:
  schedule:
    - cron: "0 0 * * 2"
  workflow_dispatch:

jobs:
  antlr:
    runs-on: ubuntu-22.04
    env:
      DEPS: debug
      Configuration: Debug
      ROOT_DIR: ${{ github.workspace }}/..
    steps:
      - name: Checkout GDL
        uses: actions/checkout@v4
      - name: Test ANTLR
        run: |
          scripts/build_gdl.sh antlr
