name: GDL CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        deps: [FULL, MINI]
        arch: [x86_64, i686]
    env:
      deps: ${{ matrix.deps }}
      platform: ${{ matrix.platform }}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
      - name: Checkout GDL
        uses: actions/checkout@v2
      - name: Build GDL
        run: |
          if ("${{ matrix.arch }}" -Match "i686") 
          {
            $env:MSYSTEM="MINGW32" ; $env:mname="mingw32" ; $env:arch="i686"
            $env:SIGNTOOL="C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\signtool.exe"
          }
          elseif ("${{ matrix.arch }}" -Match "x86_64") 
          {
            $env:MSYSTEM="MINGW64" ;  $env:mname="mingw64" ; $env:arch="x86_64"
            $env:SIGNTOOL="C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe"
          }
          ${env:ROOT_DIR} = "${{ github.workspace }}\.."
          msys2 pacman --noconfirm -S --needed mingw-w64-${{ matrix.arch }}-toolchain
          msys2 ${ROOT_DIR}/gdl/.ci/build-gdl-windows.msys prep
          msys2 ${ROOT_DIR}/gdl/.ci/build-gdl-windows.msys build
      - name: Check GDL
        run: msys2 ./.ci/build-gdl-windows.msys check
      - name: Package GDL
        run: msys2 ./.ci/build-gdl-windows.msys pack
