name: GDL CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        deps: [FULL, MINI]
        arch: [x86_64, i686]
    env:
      deps: ${{ matrix.deps }}
      platform: ${{ matrix.platform }}
      workspace: ${{ github.workspace }}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
      - name: Checkout GDL
        uses: actions/checkout@v2
      - name: Build GDL
        shell: msys2 {0}
        run: |
          export arch=${{ matrix.arch }}
          export ROOT_DIR=`cygpath ${workspace}/..`
          pacman --noconfirm -S --needed mingw-w64-${{ matrix.arch }}-toolchain
          ${ROOT_DIR}/gdl/.ci/build-gdl-windows.msys prep
          ${ROOT_DIR}/gdl/.ci/build-gdl-windows.msys build
      - name: Check GDL
        shell: msys2 {0}
        run: |
          export arch=${{ matrix.arch }}
          export ROOT_DIR=`cygpath ${workspace}/..`
          ${ROOT_DIR}/gdl/.ci/build-gdl-windows.msys check
      - name: Package GDL
        run: |
          export arch=${{ matrix.arch }}
          export ROOT_DIR=`cygpath ${workspace}/..`
          ${ROOT_DIR}/gdl/.ci/build-gdl-windows.msys pack
